import { createApp } from "vue";
import App from "./App.vue";
import { router } from "./router";
import { createI18n } from "vue-i18n";

import "./assets/index.css";

const i18n = createI18n({
  locale:
    JSON.parse(localStorage.getItem("sb-user-data") || "{}")?.user_metadata
      ?.settings?.language || "id",
  fallbackLocale: "en",
  messages: {
    id: {
      global: {
        currency: "Rp",
        thousandAbbreviation: "rb",
        millionAbbreviation: "jt",
      },
      login: {
        title: "Masuk",
        form_title: "Masuk ke akun Anda",
        form_description: "Masukkan kredensial Anda untuk mengakses akun Anda.",
        email_label: "Alamat Pos-el",
        password_label: "Kata Sandi",
        forgot_password: "Lupa kata sandi?",
        login_button: "Masuk",
      },
      sidebar: {
        logo_alt: "Lambang",
        add_new_item: "Tambah Barang Baru",
        dashboard: "Dasbor",
        items: "Barang",
        search: "Pencarian",
        tags: "Tag",
        profile_picture_alt: "Foto Profil",
        account: "Akun",
        settings: "Setelan",
        logout: "Keluar",
        login: "Masuk",
        unknown_user: "Pengguna Tidak Dikenal",
      },
      dashboard: {
        title: "Dasbor",
        inventory_summary: "Ringkasan Inventaris",
        total_categories: "Total Kategori",
        total_items: "Total Barang",
        items_deployed: "Barang Diluar Gudang",
        total_value: "Nilai Total",
        no_categories: "Tidak ada perubahan akhir ini.",
        new_categories: "Ada kategori baru nih!",
        no_new_items: "Belum ada mainan baru...",
        new_items: "Wih, ada mainan baru!",
        no_deployments: "Aman dan nyaman di rumah.",
        new_deployments: "Ada yang sok sibuk nih...",
        no_value_increase: "Dompet masih aman.",
        new_value_increase: "Dompet gimana bos; aman?",
        data_from_30d: "Data dari 30 hari terakhir",
        data_compared_yesterday: "Dibanding kemarin",
        deployed_items: "Barang yg. diluar gudang",
        deployed_on: "Dikeluarkan pada {date}",
        item_image_alt: "Gambar Barang",
      },
      account: {
        title: "Akun",
        account_settings: "Setelan Akun",
        account_settings_description: "Kelola setelan dan informasi akun Anda.",
        profile_picture: "Foto Profil",
        profile_picture_description: "PNG, JPEG, or WEBP; dibawah 2MB.",
        profile_picture_alt: "Foto Profil",
        upload_button: "Unggah",
        clear_button: "Hapus",
        display_name: "Nama Tampilan",
        display_name_fallback: "Pengguna Tidak Dikenal",
        email_address: "Alamat Pos-el",
        user_id: "ID Pengguna",
        user_id_description: "Identifikasi unik Anda. Ini tidak dapat diubah.",
        save_button: "Simpan Perubahan",
        discard_button: "Buang Perubahan",
        password_and_authentication: "Kata Sandi & Otentikasi",
        password_and_authentication_description:
          "Kelola kata sandi dan setelan otentikasi Anda.",
        change_password: "Ubah Kata Sandi",
      },
      settings: {
        title: "Setelan",
        general: "Umum",
        general_description: "Kelola setelan dan preferensi pengguna Anda",
        appearance: "Tampilan",
        appearance_light: "Terang",
        appearance_dark: "Gelap",
        appearance_system: "Ikuti Setelan Sistem",
        language: "Bahasa",
        language_placeholder: "Pilih bahasa Anda",
        save_button: "Simpan Perubahan",
        discard_button: "Buang Perubahan",
      },
    },
    en: {
      global: {
        currency: "IDR",
        thousandAbbreviation: "K",
        millionAbbreviation: "M",
      },
      login: {
        title: "Login",
        form_title: "Log in to your account",
        form_description: "Enter your credentials to access your account.",
        email_label: "Email Address",
        password_label: "Password",
        forgot_password: "Forgot your password?",
        login_button: "Log In",
      },
      sidebar: {
        logo_alt: "Logo",
        add_new_item: "Add New Item",
        dashboard: "Dashboard",
        items: "Items",
        search: "Search",
        tags: "Tags",
        profile_picture_alt: "Profile Picture",
        account: "Account",
        settings: "Settings",
        logout: "Log Out",
        login: "Log In",
        unknown_user: "Unknown User",
      },
      dashboard: {
        title: "Dashboard",
        inventory_summary: "Inventory Summary",
        total_categories: "Total Categories",
        total_items: "Total Items",
        items_deployed: "Items Deployed",
        total_value: "Total Value",
        no_new_categories: "No changes recently.",
        new_categories: "New categories were added!",
        no_new_items: "No new toys... yet.",
        new_items: "Wow, new toys!",
        no_deployments: "Safe and sound at home.",
        new_deployments: "Someone's trying to be busy...",
        no_value_increase: "No big spenders here.",
        new_value_increase: "How's the wallet?",
        data_from_30d: "Data from last 30 days",
        data_compared_yesterday: "Data compared to yesterday",
        deployed_items: "Deployed Items",
        deployed_on: "Deployed on {date}",
        item_image_alt: "Item Image",
      },
      account: {
        title: "Account",
        account_settings: "Account Settings",
        account_settings_description:
          "Manage your account settings and information.",
        profile_picture: "Profile Picture",
        profile_picture_description: "PNG, JPEG, or WEBP; under 2MB.",
        profile_picture_alt: "Profile Picture",
        upload_button: "Upload",
        clear_button: "Clear",
        display_name: "Display Name",
        display_name_fallback: "Unknown User",
        email_address: "Email Address",
        user_id: "User ID",
        user_id_description: "Your unique user ID. This cannot be changed.",
        save_button: "Save Changes",
        discard_button: "Discard",
        password_and_authentication: "Password & Authentication",
        password_and_authentication_description:
          "Manage your password and authentication settings.",
        change_password: "Change Password",
      },
      settings: {
        title: "Settings",
        general: "General",
        general_description: "Manage your user settings and preferences",
        appearance: "Appearance",
        appearance_light: "Light",
        appearance_dark: "Dark",
        appearance_system: "Follow System Setting",
        language: "Language",
        language_placeholder: "Select your language",
        save_button: "Save Changes",
        discard_button: "Discard",
      },
    },
  },
});

createApp(App).use(router).use(i18n).mount("#app");
