import { createApp } from "vue";
import App from "./App.vue";
import { router } from "./router";
import { createI18n } from "vue-i18n";

import "./assets/index.css";

const i18n = createI18n({
  locale:
    JSON.parse(localStorage.getItem("sb-user-data") || "{}")?.user_metadata
      ?.settings?.language || "id",
  fallbackLocale: "en",
  messages: {
    id: {
      language: {
        locale: "id-ID",
        units: {
          currency: "Rp",
          mass: "kg",
        },
        numberAbbreviations: {
          thousand: "rb",
          million: "jt",
          billion: "M",
        },
      },
      components: {
        error: {
          title: "Ups, ada yang salah nih!",
        },
        sidebar: {
          logo_alt: "Lambang",
          add_new_item: "Tambah Barang Baru",
          dashboard: "Dasbor",
          items: "Barang",
          search: "Pencarian",
          tags: "Tag",
          profile_picture_alt: "Foto Profil",
          account: "Akun",
          settings: "Setelan",
          logout: "Keluar",
          login: "Masuk",
          unknown_user: "Pengguna Tidak Dikenal",
        },
        context_menu: {
          item: {
            view_item: "Lihat Barang",
            deploy_item: "Tempatkan Sekarang",
            undeploy_item: "Batalkan Penempatan",
            open_in_editor: "Buka di Editor",
            rename: "Ganti Nama...",
            move_to_location: "Pindahkan Lokasi...",
            edit_person_responsible: "Ganti Penanggung Jawab...",
            delete: "Hapus",
          },
          category: {
            view_items_in_category: "Lihat Barang dalam Kategori",
            rename: "Ganti Nama...",
            delete: "Hapus",
          },
        },
        dialog: {
          rename: "Ganti Nama Barang",
          rename_description: "Masukkan nama baru untuk barang ini.",
          category_rename_description: "Masukkan nama baru untuk kategori ini.",
          move_to_location: "Pindahkan Barang ke Lokasi Baru",
          move_to_location_description:
            "Masukkan lokasi baru untuk barang ini. Ini dapat digunakan untuk melacak di mana barang Anda berada.",
          edit_person_responsible: "Ganti Penanggung Jawab",
          edit_person_responsible_description:
            "Masukkan nama orang yang bertanggung jawab untuk barang ini. Ini dapat digunakan untuk melacak siapa yang bertanggung jawab atas barang-barang tertentu.",
          generic_cancel: "Batal",
          generic_confirm: "Simpan Perubahan",
          delete: "Apakah Anda benar-benar yakin?",
          delete_description:
            "Tindakan ini tidak dapat dibatalkan. Ini akan menghapus barang ini secara permanen dan menghilangkannya dari inventaris Anda.",
          category_delete_description:
            "Tindakan ini tidak dapat dibatalkan. Barang yang termasuk dalam kategori ini tidak akan dihapus, tetapi akan dikategorikan ulang sebagai 'Tidak Dikategorikan'.",
          delete_cancel: "Gajadi, deh..",
          delete_confirm: "Yakin, hapus aja!",
        },
      },
      pages: {
        404: {
          title: "Halaman Tidak Ditemukan",
          description: "Halaman yang Anda cari tidak ditemukan.",
          suggestion:
            "Halaman tersebut mungkin telah dihapus atau Anda memasukkan URL yang salah.",
        },
        login: {
          title: "Masuk",
          form_title: "Masuk ke akun Anda",
          form_description:
            "Masukkan kredensial Anda untuk mengakses akun Anda.",
          email_label: "Alamat Pos-el",
          password_label: "Kata Sandi",
          forgot_password: "Lupa kata sandi?",
          login_button: "Masuk",
        },
        dashboard: {
          title: "Dasbor",
          inventory_summary: "Ringkasan Inventaris",
          total_categories: "Total Kategori",
          total_items: "Total Barang",
          items_deployed: "Barang yg. Ditempatkan",
          total_value: "Nilai Total",
          no_categories: "Tidak ada perubahan akhir ini.",
          new_categories: "Ada kategori baru nih!",
          no_new_items: "Belum ada mainan baru...",
          new_items: "Wih, ada mainan baru!",
          no_deployments: "Aman dan nyaman di rumah.",
          new_deployments: "Ada yang sok sibuk nih...",
          no_value_increase: "Dompet masih aman.",
          new_value_increase: "Dompet gimana bos; aman?",
          data_from_30d: "Data dari 30 hari terakhir",
          data_compared_yesterday: "Dibanding kemarin",
          deployed_items: "Barang yg. Ditempatkan",
          deployed_on: "Dikeluarkan pada {date}",
          deployed_on_with_at: "Dikeluarkan {date} di {location}",
          item_image_alt: "Gambar Barang",
        },
        items: {
          title: "Barang",
          categories: "Kategori",
          all_items: "Semua Barang",
          items_in_category: "Barang dalam {category}",
          new_category: "Kategori Baru",
          new_category_description:
            "Buat kategori baru untuk mengorganisir barang Anda.",
          create_category: "Buat Kategori",
          new_category_name: "Nama",
          viewer: {
            go_back: "Kembali ke Barang",
            name_placeholder: "Barang Tanpa Nama",
            edit_item: "Edit Barang",
            delete_item: "Hapus Barang",
            unknown_category: "Tidak Dikategorikan",
            unknown_tag: "Tag Tidak Dikenal",
            mass: "Massa",
            price: "Harga",
            deployment_status: "Status Penempatan",
            not_deployed: "Aman dan nyaman di rumah.",
            deployed_on: "Dikeluarkan pada",
            deployed_at: "Ditempatkan di",
            person_responsible: "Penanggung Jawab",
            remarks: "Catatan",
            remarks_placeholder: "Catatan tambahan ditambahkan di sini, ya!",
            created_at: "Dibuat pada",
            unique_id: "ID Unik",
            save_item: "Simpan Barang",
            delete_confirmation: "Apakah Anda benar-benar yakin?",
            delete_warning:
              "Tindakan ini tidak dapat dibatalkan. Ini akan menghapus barang ini secara permanen dan menghilangkannya dari inventaris Anda.",
            delete_cancel: "Gajadi, deh..",
            delete_confirm: "Yakin, hapus aja!",
          },
          editor: {
            create_item: "Membuat '{name}'",
            edit_item: "Mengedit '{name}'",
            save_item: "Simpan Barang",
            discard_changes: "Buang Perubahan",
            name: "Nama Barang",
            name_placeholder: "Masukkan nama barang",
            category: "Kategori",
            category_placeholder: "Kategorikan barang Anda",
            unknown_category: "Tidak Dikategorikan",
            tags: "Tag",
            tags_placeholder: "Tambahkan tag untuk barang Anda",
            mass: "Massa",
            price: "Harga",
            view_qr_code: "Lihat Kode QR",
            view_qr_code_popover_title: "Kode QR",
            view_qr_code_popover_description:
              "Ini adalah kode QR untuk barang ini. Anda dapat memindai ini di perangkat apa pun untuk kembali ke halaman ini.",
            view_barcode: "Lihat Barcode",
            view_barcode_popover_title: "Barcode",
            view_barcode_popover_description:
              "Ini adalah barcode untuk barang ini. Anda dapat memindai ini di website ini untuk melihat detailnya.",
            add_image: "Tambah Gambar",
            replace_image: "Ganti Gambar",
            remove_image: "Hapus Gambar",
            custom_fields: "Bidang Kustom",
            custom_field_key: "Nama",
            custom_field_value: "Isi",
            created_at: "Dibuat pada",
            unique_id: "ID Unik",
            remarks: "Catatan",
            remarks_placeholder: "Catatan tambahan ditambahkan di sini, ya!",
            is_deployed: "Barang ini sedang ditempatkan.",
            deployed_date: "Tanggal Penempatan",
            deployed_at: "Lokasi Penempatan",
            deployed_at_placeholder: "Di mana barang ini ditempatkan?",
            person_responsible: "Penanggung Jawab",
            person_responsible_placeholder:
              "Siapa yang bertanggung jawab atas penempatan ini?",
          },
        },
        search: {
          title: "Pencarian",
        },
        account: {
          title: "Akun",
          account_settings: "Setelan Akun",
          account_settings_description:
            "Kelola setelan dan informasi akun Anda.",
          profile_picture: "Foto Profil",
          profile_picture_description: "PNG, JPEG, or WEBP; dibawah 2MB.",
          profile_picture_alt: "Foto Profil",
          upload_button: "Unggah",
          clear_button: "Hapus",
          display_name: "Nama Tampilan",
          display_name_fallback: "Pengguna Tidak Dikenal",
          email_address: "Alamat Pos-el",
          user_id: "ID Pengguna",
          user_id_description:
            "Identifikasi unik Anda. Ini tidak dapat diubah.",
          save_button: "Simpan Perubahan",
          discard_button: "Buang Perubahan",
          password_and_authentication: "Kata Sandi & Otentikasi",
          password_and_authentication_description:
            "Kelola kata sandi dan setelan otentikasi Anda.",
          change_password: "Ubah Kata Sandi",
        },
        settings: {
          title: "Setelan",
          general: "Umum",
          general_description: "Kelola setelan dan preferensi pengguna Anda",
          appearance: "Tampilan",
          appearance_light: "Terang",
          appearance_dark: "Gelap",
          appearance_system: "Ikuti Setelan Sistem",
          language: "Bahasa",
          language_placeholder: "Pilih bahasa Anda",
          save_button: "Simpan Perubahan",
          discard_button: "Buang Perubahan",
        },
      },
    },
    en: {
      language: {
        locale: "en-UK",
        units: {
          currency: "IDR",
          mass: "kg",
        },
        numberAbbreviations: {
          thousand: "K",
          million: "M",
          billion: "B",
        },
      },
      components: {
        error: {
          title: "Uh-oh, something went wrong.",
        },
        sidebar: {
          logo_alt: "Logo",
          add_new_item: "Add New Item",
          dashboard: "Dashboard",
          items: "Items",
          search: "Search",
          tags: "Tags",
          profile_picture_alt: "Profile Picture",
          account: "Account",
          settings: "Settings",
          logout: "Log Out",
          login: "Log In",
          unknown_user: "Unknown User",
        },
        context_menu: {
          item: {
            view_item: "View Item",
            deploy_item: "Quick Deploy",
            undeploy_item: "Undeploy Item",
            open_in_editor: "Open In Editor",
            rename: "Rename...",
            move_to_location: "Move To Location...",
            edit_person_responsible: "Edit Person Responsible...",
            delete: "Delete",
          },
          category: {
            view_items_in_category: "View Items in Category",
            rename: "Rename...",
            delete: "Delete",
          },
        },
        dialog: {
          rename: "Rename Item",
          rename_description: "Enter a new name for this item.",
          category_rename_description: "Enter a new name for this category.",
          move_to_location: "Move Item To New Location",
          move_to_location_description:
            "Enter a new location for this item. This can be used to track where your items are.",
          edit_person_responsible: "Edit Person Responsible",
          edit_person_responsible_description:
            "Enter the name of the person responsible for this item. This can be used to keep track of who is responsible for which items.",
          generic_cancel: "Cancel",
          generic_confirm: "Save Changes",
          delete: "Are you absolutely sure?",
          delete_description:
            "This action cannot be undone. This will permanently delete the item and remove it from your inventory.",
          category_delete_description:
            "This action cannot be undone. Items that are in this category will not be deleted, but will be recategorized as 'Uncategorised'.",
          delete_cancel: "Nevermind!",
          delete_confirm: "I'm sure, delete it!",
        },
      },
      pages: {
        404: {
          title: "Page Not Found",
          description: "The page you are looking for does not exist.",
          suggestion:
            "It might have been removed or you may have entered the wrong URL.",
        },
        login: {
          title: "Login",
          form_title: "Log in to your account",
          form_description: "Enter your credentials to access your account.",
          email_label: "Email Address",
          password_label: "Password",
          forgot_password: "Forgot your password?",
          login_button: "Log In",
        },
        dashboard: {
          title: "Dashboard",
          inventory_summary: "Inventory Summary",
          total_categories: "Total Categories",
          total_items: "Total Items",
          items_deployed: "Items Deployed",
          total_value: "Total Value",
          no_categories: "No changes recently.",
          new_categories: "New categories were added!",
          no_new_items: "No new toys... yet.",
          new_items: "Wow, new toys!",
          no_deployments: "Safe and sound at home.",
          new_deployments: "Someone's trying to be busy...",
          no_value_increase: "No big spenders here.",
          new_value_increase: "How's the wallet?",
          data_from_30d: "Data from last 30 days",
          data_compared_yesterday: "Data compared to yesterday",
          deployed_items: "Deployed Items",
          deployed_on: "Deployed on {date}",
          deployed_on_with_at: "Deployed {date} at {location}",
          item_image_alt: "Item Image",
        },
        items: {
          title: "Items",
          categories: "Categories",
          all_items: "All Items",
          items_in_category: "Items in {category}",
          new_category: "New Category",
          new_category_description: "Create a new category to organize items.",
          new_category_name: "Name",
          create_category: "Create Category",
          viewer: {
            go_back: "Go Back to Items",
            name_placeholder: "Unnamed Item",
            edit_item: "Edit Item",
            delete_item: "Delete Item",
            unknown_category: "Uncategorised",
            unknown_tag: "Unknown Tag",
            mass: "Mass",
            price: "Price",
            deployment_status: "Deployment Status",
            not_deployed: "Safe and sound at home.",
            deployed_on: "Deployed on",
            deployed_at: "Deployed at",
            person_responsible: "Person Responsible",
            remarks: "Remarks",
            remarks_placeholder: "Any additional notes can be added here!",
            created_at: "Created At",
            unique_id: "Unique Identifier",
            delete_confirmation: "Are you absolutely sure?",
            delete_warning:
              "This action cannot be undone. This will permanently delete the item and remove it from your inventory.",
            delete_cancel: "Nevermind!",
            delete_confirm: "I'm sure, delete it!",
          },
          editor: {
            create_item: "Creating '{name}'",
            edit_item: "Editing '{name}'",
            save_item: "Save Item",
            discard_changes: "Discard Changes",
            name: "Item Name",
            name_placeholder: "Enter item name",
            category: "Category",
            category_placeholder: "Categorise your item",
            unknown_category: "Uncategorised",
            tags: "Tags",
            tags_placeholder: "Add some tags for your item",
            mass: "Mass",
            price: "Price",
            view_qr_code: "View QR Code",
            view_qr_code_popover_title: "QR Code",
            view_qr_code_popover_description:
              "Here's the QR code for this item. You can scan this on any device to go back to this page.",
            view_barcode: "View Barcode",
            view_barcode_popover_title: "Barcode",
            view_barcode_popover_description:
              "Here's the barcode for this item. You can scan this on this website to view its details.",
            add_image: "Add Image",
            replace_image: "Replace Image",
            remove_image: "Remove Image",
            custom_fields: "Custom Fields",
            custom_field_key: "Key",
            custom_field_value: "Value",
            created_at: "Created At",
            unique_id: "Unique Identifier",
            remarks: "Remarks",
            remarks_placeholder: "Any additional notes can be added here!",
            is_deployed: "This item is currently deployed.",
            deployed_date: "Deployment Date",
            deployed_at: "Deployment Location",
            deployed_at_placeholder: "Where is this item deployed?",
            person_responsible: "Person Responsible",
            person_responsible_placeholder:
              "Who is responsible for this deployment?",
          },
        },
        search: {
          title: "Search",
        },
        account: {
          title: "Account",
          account_settings: "Account Settings",
          account_settings_description:
            "Manage your account settings and information.",
          profile_picture: "Profile Picture",
          profile_picture_description: "PNG, JPEG, or WEBP; under 2MB.",
          profile_picture_alt: "Profile Picture",
          upload_button: "Upload",
          clear_button: "Clear",
          display_name: "Display Name",
          display_name_fallback: "Unknown User",
          email_address: "Email Address",
          user_id: "User ID",
          user_id_description: "Your unique user ID. This cannot be changed.",
          save_button: "Save Changes",
          discard_button: "Discard",
          password_and_authentication: "Password & Authentication",
          password_and_authentication_description:
            "Manage your password and authentication settings.",
          change_password: "Change Password",
        },
        settings: {
          title: "Settings",
          general: "General",
          general_description: "Manage your user settings and preferences",
          appearance: "Appearance",
          appearance_light: "Light",
          appearance_dark: "Dark",
          appearance_system: "Follow System Setting",
          language: "Language",
          language_placeholder: "Select your language",
          save_button: "Save Changes",
          discard_button: "Discard",
        },
      },
    },
  },
});

createApp(App).use(router).use(i18n).mount("#app");
